// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type App struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Image       string `json:"image"`
	Description string `json:"description"`
}

type CashFlow struct {
	Categories []*string  `json:"categories,omitempty"`
	Cash       []*float64 `json:"cash,omitempty"`
}

type City struct {
	ID     int    `json:"id"`
	Name   string `json:"name"`
	NameAr string `json:"name_ar"`
}

type Dashboard struct {
	RecentApps   []*App        `json:"recentApps"`
	ProductViews *ProductViews `json:"productViews"`
	ProductsBar  *ProductsBar  `json:"productsBar"`
	CashFlow     *CashFlow     `json:"cashFlow"`
}

type Department struct {
	DepartmentID  string  `json:"departmentID"`
	Title         string  `json:"title"`
	ArabicTitle   string  `json:"arabicTitle"`
	Schools       string  `json:"schools"`
	Description   string  `json:"description"`
	DescriptionAr string  `json:"description_ar"`
	Grades        []*Grad `json:"grades"`
}

type Grad struct {
	GradID      string     `json:"gradID"`
	Title       string     `json:"title"`
	ArabicTitle string     `json:"arabicTitle"`
	Subjects    []*Subject `json:"subjects"`
}

type Mutation struct {
}

type OperationStatus struct {
	Succeeded bool `json:"succeeded"`
}

type ProductViews struct {
	Categories []*string `json:"categories,omitempty"`
	Products   []*string `json:"products,omitempty"`
	Views      []*int    `json:"views,omitempty"`
}

type ProductsBar struct {
	Labels   []*string `json:"labels,omitempty"`
	Products []*string `json:"products,omitempty"`
}

type Query struct {
}

type Subject struct {
	SubjectID   string  `json:"subjectID"`
	Title       string  `json:"title"`
	ArabicTitle string  `json:"arabicTitle"`
	Grads       []*Grad `json:"grads"`
}
