// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Department struct {
	DepartmentID  string  `json:"departmentID"`
	Title         string  `json:"title"`
	ArabicTitle   string  `json:"arabicTitle"`
	Schools       string  `json:"schools"`
	Description   string  `json:"description"`
	DescriptionAr string  `json:"description_ar"`
	Grades        []*Grad `json:"grades"`
}

type Grad struct {
	GradID      string     `json:"gradID"`
	Title       string     `json:"title"`
	ArabicTitle string     `json:"arabicTitle"`
	Subjects    []*Subject `json:"subjects"`
}

type Mutation struct {
}

type OperationStatus struct {
	Succeeded bool `json:"succeeded"`
}

type Query struct {
}

type Subject struct {
	SubjectID   string  `json:"subjectID"`
	Title       string  `json:"title"`
	ArabicTitle string  `json:"arabicTitle"`
	Grads       []*Grad `json:"grads"`
}
